apiVersion: apps/v1
kind: Deployment
metadata:
  name: "httpd-deployment"
spec:
  selector:
    matchLabels:
      app: "httpd"
  replicas: 3
  template:
    metadata:
      labels:
        app: "httpd"
    spec:
      containers:
      - name: "nginx"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
